/**
 * Resolves an ImageRef's manifest `base` key into the full responsive image
 * data Image.tsx needs — AVIF/WebP srcset strings, a JPEG fallback src,
 * natural width/height, and the LQIP base64 placeholder.
 *
 * public/img/manifest.json is generated by scripts/photos.mjs (see
 * docs/04-photography.md §4) and imported here as a static JSON module —
 * Vite bundles it at build time, so resolving an image costs no network
 * request beyond the actual image files.
 */
import manifest from '../../public/img/manifest.json';
import type { ImageRef } from './types';

interface ManifestEntry {
  width: number;
  height: number;
  lqip: string;
  avifWidths: number[];
  webpWidths: number[];
  fallback: string;
}

const MANIFEST: Record<string, ManifestEntry> = manifest;

export interface ResolvedImage {
  alt: string;
  caption?: string;
  width: number;
  height: number;
  lqip: string;
  avifSrcSet: string;
  webpSrcSet: string;
  fallbackSrc: string;
}

function buildSrcSet(site: string, base: string, format: 'avif' | 'webp', widths: number[]): string {
  return widths.map((w) => `/img/${site}/${base}-${w}.${format} ${w}w`).join(', ');
}

/**
 * Resolves an ImageRef against the generated manifest. Throws if the
 * referenced base doesn't exist — a missing image should fail loudly (like
 * the rest of this content layer's validation), not render a broken <img>.
 */
export function resolveImage(ref: ImageRef): ResolvedImage {
  const entry = MANIFEST[ref.base];
  if (!entry) {
    throw new Error(
      `[content] ImageRef base "${ref.base}" has no entry in public/img/manifest.json — run \`npm run photos\` or fix the base name.`,
    );
  }

  const slashIndex = ref.base.indexOf('/');
  const site = ref.base.slice(0, slashIndex);
  const base = ref.base.slice(slashIndex + 1);

  return {
    alt: ref.alt,
    caption: ref.caption,
    width: entry.width,
    height: entry.height,
    lqip: entry.lqip,
    avifSrcSet: buildSrcSet(site, base, 'avif', entry.avifWidths),
    webpSrcSet: buildSrcSet(site, base, 'webp', entry.webpWidths),
    fallbackSrc: entry.fallback,
  };
}
